baseURL = 'https://seismobassoon.github.io/'

theme = "PaperMod"
title = 'Nobuaki Fuji'
  
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
enableRobotsTXT = true
languageCode = 'en'




disablePathToLower = false


[params]
    displayFullLangName = false
    ShowReadingTime = false
    ShowBreadCrumbs = false
    ShowPostNavLinks = false
    googleSiteVerification = "YxiAZLMcK1ogVJx0r_32wyQ2IGTOVBJBA9tbF-y0piY"
    [params.analytics.google]
          SiteVerificationTag = "YxiAZLMcK1ogVJx0r_32wyQ2IGTOVBJBA9tbF-y0piY"

    [params.assets]
        customCSS = ["css/custom.css"]

    [params.profileMode]
        enabled = true
        title = "Nobuaki Fuji"
        subtitle = "Geophysics • Art & Science"
        imageUrl = "images/moi.png"
        imageWidth = 180
        imageHeight = 160
    

    [[params.socialIcons]]
        name = "googlescholar"
        url = "https://scholar.google.com/citations?user=EqiISYkAAAAJ"

    [[params.socialIcons]]
        name = "linkedin"
        url = "https://www.linkedin.com/in/nobuaki-fuji-82ba9520"

    [[params.socialIcons]]
        name = "youtube"
        url = "https://www.youtube.com/@seismobassoon"


    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/seismobassoon"
        
        
        

        

[languages]

  [languages.en]
    weight = 1
    languageName ="English"
    languageCode = "en"
    contentDir = "content/en"
    [languages.en.params]
      langBadge = "EN"
      
    [[languages.en.menu.main]]
        name = "📢"
        pre = "News"
        url = "news/"
        weight = 1
    [[languages.en.menu.main]]
        name = "👤"
        pre = "About"
        url = "cv/"
        weight = 2
    [[languages.en.menu.main]]
        name = "👥"
        pre = "Team"
        url = "team/"
        weight = 3
    [[languages.en.menu.main]]
        name = "🧠"
        pre = "Research"
        url = "research/"
        weight = 4
    [[languages.en.menu.main]]
        name = "🎓"
        pre = "Publications"
        pageRef = "publications/"
        weight = 5
    [[languages.en.menu.main]]
        name = "🏫"
        pre = "Education"
        url = "education/"
        weight = 6
    [[languages.en.menu.main]]
        name = "🎹"
        pre = "PhiloGaïa"
        url = "geomusic/"
        weight = 7

        
  [languages.fr]
    weight = 2
    languageName = "Français"
    contentDir = "content/fr"
    [languages.fr.params]
      langBadge = "FR"
    [[languages.fr.menu.main]]
        name = "📢"
        pre = "actu"
        url = "news/"
        weight = 1
    [[languages.fr.menu.main]]
        name = "👤"
        pre = "moi"
        url = "cv/"
        weight = 2
    [[languages.fr.menu.main]]
        name = "👥"
        pre = "équipe"
        url = "team/"
        weight = 3
    [[languages.fr.menu.main]]
        name = "🧠"
        pre = "recherche"
        url = "research/"
        weight = 4
    [[languages.fr.menu.main]]
        name = "🎓"
        pre = "Publications"
        pageRef = "publications/"
        weight = 5
        
    [[languages.fr.menu.main]]
        name = "🏫"
        pre = "enseignement"
        url = "education/"
        weight = 6
    [[languages.fr.menu.main]]
        name = "🎹"
        pre = "philogaïa"
        url = "geomusic/"
        weight = 7
    




    
  [languages.jp]
    weight = 3
    languageName = "日本語"
    contentDir = "content/jp"
    [languages.jp.params]
      langBadge = "あ"
    [[languages.jp.menu.main]]
        name = "📢"
        pre = "ニュース"
        url = "news/"
        weight = 1
    [[languages.jp.menu.main]]
        name = "👤"
        pre = "私"
        url = "cv/"
        weight = 2
    [[languages.jp.menu.main]]
        name = "👥"
        pre = "研究室"
        url = "team/"
        weight = 3
    [[languages.jp.menu.main]]
        name = "🧠"
        pre = "研究"
        url = "research/"
        weight = 4
    [[languages.jp.menu.main]]
        name = "🎓"
        pre = "Publications"
        pageRef = "publications/"
        weight = 5
    [[languages.jp.menu.main]]
        name = "🏫"
        pre = "教育"
        url = "education/"
        weight = 6
    [[languages.jp.menu.main]]
        name = "🎹"
        pre = "フィロガイア"
        url = "geomusic/"
        weight = 7




  [languages.de]
  weight = 4
  languageName = "Deutsch"
  contentDir = "content/de"
  [languages.de.params]
    langBadge = "DE"

  [[languages.de.menu.main]]
      name = "📢"
      pre = "Aktuelles"
      url = "news/"
      weight = 1

  [[languages.de.menu.main]]
      name = "👤"
      pre = "Über mich"
      url = "cv/"
      weight = 2

  [[languages.de.menu.main]]
      name = "👥"
      pre = "Team"
      url = "team/"
      weight = 3

  [[languages.de.menu.main]]
      name = "🧠"
      pre = "Forschung"
      url = "research/"
      weight = 4

   [[languages.de.menu.main]]
        name = "🎓"
        pre = "Publications"
        pageRef = "publications/"
        weight = 5

  [[languages.de.menu.main]]
      name = "🏫"
      pre = "Lehre"
      url = "education/"
      weight = 6

  [[languages.de.menu.main]]
      name = "🎹"
      pre = "Philogaia"
      url = "geomusic/"
      weight = 7

   
    
  [languages.no]
    weight = 5
    languageName = "Bokmål"
    contentDir = "content/no"
    [languages.no.params]
      langBadge = "NO"
    [[languages.no.menu.main]]
        name = "📢"
        pre = "Nyheter"
        url = "news/"
        weight = 1
    [[languages.no.menu.main]]
        name = "👤"
        pre = "Meg"
        url = "cv/"
        weight = 2
    [[languages.no.menu.main]]
        name = "👥"
        pre = "Gruppe"
        url = "team/"
        weight = 3
    [[languages.no.menu.main]]
        name = "🧠"
        pre = "Forskning"
        url = "research/"
        weight = 4
    [[languages.no.menu.main]]
        name = "🏫"
        pre = "Undervisning"
        url = "education/"
        weight = 6
    [[languages.no.menu.main]]
        name = "🎹"
        pre = "PhiloGaïa"
        url = "geomusic/"
        weight = 7
