name: Build and Deploy Hugo Site

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # récupérer le dépôt
      - name: Checkout repository
        uses: actions/checkout@v4

      # installer Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.121.2'
          extended: true

      # construire le site
      - name: Build
        run: hugo --minify

      # déployer sur GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public